import { CustomersCreateFormData } from "../features/customers/Form";

export const customersMock = [
  {
    id: "1",
    name: "Erick Pascoal",
    phoneNumber: "27988846549",
    contactPhoneNumber: "27998465522",
    email: "erickpascoal@teste.com",
    address: "Travessa rua antonio ataide",
    zipCode: "29107185",
    city: "Vila velha",
    district: "Divino",
    uf: "ES",
  },
  {
    id: "2",
    name: "Kelvi Pascoal",
    phoneNumber: "27993219875",
    contactPhoneNumber: "",
    email: "Kelvi@teste.com",
    address: "Travessa rua antonio ataide",
    zipCode: "29107185",
    city: "Vila velha",
    district: "Divino",
    uf: "ES",
  },
  {
    id: "3",
    name: "Seju Pascoal",
    phoneNumber: "27999887777",
    contactPhoneNumber: "",
    email: "seju@teste.com",
    address: "Travessa rua antonio ataide",
    zipCode: "29107185",
    city: "Vila velha",
    district: "Divino",
    uf: "ES",
  },
];

export const customers = [
  {
    name: "Jhon Wick",
    email: "wick@hotmail.com",
    address: "Travessa Antônio Ataíde",
    district: "Divino Espírito Santo",
    city: "Vila Velha",
    uf: "ES",
    phoneNumber: "32992132132",
    contactPhoneNumber: "",
    zipCode: "29 107 185",
    id: "5a0FKFx",
  },
  {
    name: "Lee Sin",
    email: "lee_sin@test.com",
    address: "Travessa Antônio Ataíde",
    district: "Divino Espírito Santo",
    city: "Vila Velha",
    uf: "ES",
    phoneNumber: "99999999999",
    contactPhoneNumber: "",
    zipCode: "29 107 185",
    id: "4hEOwIR",
  },
  {
    name: "Erick Pascoal",
    email: "erickpascoal@teste.com",
    address: "Travessa rua antonio ataide",
    district: "Divino",
    city: "Vila velha",
    uf: "ES",
    phoneNumber: "27988846549",
    contactPhoneNumber: "27998465522",
    zipCode: "29107185",
    id: "nDW5-8S",
  },
  {
    name: "Kelvi Pascoal",
    email: "Kelvi@teste.com",
    address: "Travessa rua antonio ataide",
    district: "Divino",
    city: "Vila velha",
    uf: "ES",
    phoneNumber: "27993219875",
    contactPhoneNumber: "",
    zipCode: "29107185",
    id: "GaG0Gmw",
  },
  {
    name: "Seju Pascoal dos Santos",
    email: "seju@teste.com",
    address: "Travessa rua antonio ataide",
    district: "Divino",
    city: "Vila velha",
    uf: "ES",
    phoneNumber: "27999887777",
    contactPhoneNumber: "",
    zipCode: "29107185",
    id: "auU7Bbt",
  },
];

export const serviceOrder = [
  {
    id: "df32g1df3",
    number: "001",
    status: "Orçamento",
    type: "Manutenção Mobile",
    description: "trocar tela de um Iphone pro max bla bla bla, e formatar",
    payment: {
      formOfPayment: "Credito",
      price: "500",
    },
    customer: {
      id: "GaG0Gmw",
      name: "Kelvi Pascoal",
    },
    endDate: "30/10/2022",
  },
];
