import { CustomersCreateFormData } from "../features/customers/Form";

export const customersMock = [
  {
    id: "1",
    name: "Erick Pascoal",
    phoneNumber: "27988846549",
    contactPhoneNumber: "27998465522",
    email: "erickpascoal@teste.com",
    address: "Travessa rua antonio ataide",
    zipCode: "29107185",
    city: "Vila velha",
    district: "Divino",
    uf: "ES",
  },
  {
    id: "2",
    name: "Kelvi Pascoal",
    phoneNumber: "27993219875",
    contactPhoneNumber: "",
    email: "Kelvi@teste.com",
    address: "Travessa rua antonio ataide",
    zipCode: "29107185",
    city: "Vila velha",
    district: "Divino",
    uf: "ES",
  },
  {
    id: "3",
    name: "Seju Pascoal",
    phoneNumber: "27999887777",
    contactPhoneNumber: "",
    email: "seju@teste.com",
    address: "Travessa rua antonio ataide",
    zipCode: "29107185",
    city: "Vila velha",
    district: "Divino",
    uf: "ES",
  },
];
