import { CustomersCreateFormData } from "../features/customers/Form";

export const customersMock = [
  {
    id: "1",
    name: "Erick Pascoal",
    phoneNumber: "(27) 9.9999-9999",
    contactPhoneNumber: "",
    email: "erickpascoal@teste.com",
    address: "Travessa rua antonio ataide",
    cep: "29107185",
    city: "Vila velha",
    district: "Divino",
    uf: "ES",
  },
  {
    id: "2",
    name: "Kelvi Pascoal",
    phoneNumber: "(27) 9.9999-9999",
    contactPhoneNumber: "",
    email: "Kelvi@teste.com",
    address: "Travessa rua antonio ataide",
    cep: "29107185",
    city: "Vila velha",
    district: "Divino",
    uf: "ES",
  },
  {
    id: "3",
    name: "Seju Pascoal",
    phoneNumber: "(27) 9.9999-9999",
    contactPhoneNumber: "",
    email: "seju@teste.com",
    address: "Travessa rua antonio ataide",
    cep: "29107185",
    city: "Vila velha",
    district: "Divino",
    uf: "ES",
  },
];
